### PR TITLE
Resolve promise only if appears successful

### PR DESCRIPTION
**Pull request by eboshii**
Optional error handler to call in the event that the observable throws an exception.

### CODE REVIEW

**Comment by mwhitworth** [comment]
> Passing an error handler to subscribe didn't work as required.

Could you provide more detail here? In what way did it not work? (for the record)

**Comment by eboshii** [comment]
> > Passing an error handler to subscribe didn't work as required.
> 
> Could you provide more detail here? In what way did it not work? (for the record)

Simply passing the error handler callback appeared to prevent the promise from resolving. I couldn't see why but this is worth me continuing to debug for the reason mentioned here in fact. https://github.com/tallarium/tron/pull/1730

**Review by mwhitworth — APPROVED** [review]
Can you update the PR description? What is described and the solution we eventually adopted do not match

**Comment by eboshii** [comment]
> Can you update the PR description? What is described and the solution we eventually adopted do not match

Yeah of course

**Pull request merged**
